
project_id = "grebpkcwmurbxorodiyb"
organization_id = "123"
tests = false

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[storage]
file_size_limit = "50MiB"

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"

[auth.email]
enabled = true
template_dir = env(SUPABASE_AUTH_EMAIL_TEMPLATE_DIR)
default_email_from = ""
default_email_name = ""
custom_template_dir = "supabase/templates/emails"

[auth.sms]
enabled = false

[functions]
serve_port = 54328
functions_port = 54327

[functions.magazine-research]
verify_jwt = true

[functions.plan-editorial-calendar]
verify_jwt = true

[functions.test-llm-prompt]
verify_jwt = true

[functions.update-news-content]
verify_jwt = true

[functions.generate-article]
verify_jwt = true

[functions.analyze-news-clusters]
verify_jwt = true

[functions.run-news-import]
verify_jwt = true

[functions.fetch-perplexity-news]
verify_jwt = true

[functions.update-scheduled-job]
verify_jwt = true

[functions.check-cron-status]
verify_jwt = true
