
project_id = "grebpkcwmurbxorodiyb"

[api]
enabled = true
port = 8080
schemas = ["public", "storage"]

[db]
port = 5432

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
port = 9999
uri_allow_list = ["https://localhost:3000"]

[functions]
[functions.test-llm-prompt]
verify_jwt = true
