// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grebpkcwmurbxorodiyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZWJwa2N3bXVyYnhvcm9kaXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODg5NzcsImV4cCI6MjA2MTg2NDk3N30.HuJWb1GhJrSD5vqeBhOn6lxcqPN9B4oX-eu1nJvsc68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);